import type { Customer } from "@/types/domain";

type CustomerProfile = Omit<Customer, "outstandingBalance" | "lastOrderDate">;

export const customerProfiles: CustomerProfile[] = [
  {
    id: "cust-atelier-north",
    name: "Nigar Rahimova",
    company: "Atelier North",
    region: "Baku, Azerbaijan",
    email: "hello@ateliernorth.demo",
    tier: "signature",
    preferredCollection: "Soft Weave Essentials",
    totalOrders: 18,
  },
  {
    id: "cust-caspian-loom",
    name: "Samir Asadov",
    company: "Caspian Loom House",
    region: "Ganja, Azerbaijan",
    email: "procurement@caspianloom.demo",
    tier: "growth",
    preferredCollection: "Premium Linen Studio",
    totalOrders: 11,
  },
  {
    id: "cust-riviera-hotel",
    name: "Leyla Mammadli",
    company: "Riviera Hotel Supply",
    region: "Tbilisi, Georgia",
    email: "ops@rivierahotel.demo",
    tier: "signature",
    preferredCollection: "Hospitality Jacquards",
    totalOrders: 25,
  },
  {
    id: "cust-saffron-home",
    name: "Aysel Karim",
    company: "Saffron Home Studio",
    region: "Istanbul, Turkiye",
    email: "studio@saffronhome.demo",
    tier: "studio",
    preferredCollection: "Organic Cotton Blend",
    totalOrders: 7,
  },
  {
    id: "cust-metro-tailor",
    name: "Elvin Hasanli",
    company: "Metro Tailor Group",
    region: "Baku, Azerbaijan",
    email: "buying@metrotailor.demo",
    tier: "growth",
    preferredCollection: "Structured Suiting Line",
    totalOrders: 14,
  },
  {
    id: "cust-amber-atelier",
    name: "Gunel Aliyeva",
    company: "Amber Atelier",
    region: "Sheki, Azerbaijan",
    email: "orders@amberatelier.demo",
    tier: "studio",
    preferredCollection: "Velvet Accent Stories",
    totalOrders: 6,
  },
  {
    id: "cust-loom-line",
    name: "Farid Nabiyev",
    company: "Loom & Line Concept",
    region: "Doha, Qatar",
    email: "projects@loomline.demo",
    tier: "growth",
    preferredCollection: "Coastal Drapery Edit",
    totalOrders: 9,
  },
  {
    id: "cust-harbor-bespoke",
    name: "Rana Suleyman",
    company: "Harbor Bespoke Interiors",
    region: "Aktau, Kazakhstan",
    email: "design@harborbespoke.demo",
    tier: "signature",
    preferredCollection: "Heritage Wool Boucle",
    totalOrders: 13,
  },
];
