import { fabricProductSchema } from "@/types/domain";

export const demoFabrics = fabricProductSchema.array().parse([
  {
    id: "fab-soft-weave",
    sku: "FL-101",
    name: "Soft Weave Cotton",
    category: "Cotton",
    composition: "92% Cotton / 8% Elastane",
    colorway: "Stone Sand",
    widthCm: 148,
    weightGsm: 220,
    stockMeters: 4800,
    reservedMeters: 1350,
    unitPrice: 34,
    status: "available",
  },
  {
    id: "fab-premium-linen",
    sku: "FL-118",
    name: "Premium Linen Studio",
    category: "Linen",
    composition: "100% Linen",
    colorway: "Warm Oat",
    widthCm: 150,
    weightGsm: 245,
    stockMeters: 1180,
    reservedMeters: 860,
    unitPrice: 49,
    status: "low",
  },
  {
    id: "fab-jacquard-hotel",
    sku: "FL-205",
    name: "Hospitality Jacquard",
    category: "Jacquard",
    composition: "67% Polyester / 33% Cotton",
    colorway: "Harbor Blue",
    widthCm: 145,
    weightGsm: 310,
    stockMeters: 2180,
    reservedMeters: 1260,
    unitPrice: 56,
    status: "reserved",
  },
  {
    id: "fab-organic-blend",
    sku: "FL-132",
    name: "Organic Cotton Blend",
    category: "Blend",
    composition: "70% Organic Cotton / 30% Viscose",
    colorway: "Olive Mist",
    widthCm: 146,
    weightGsm: 210,
    stockMeters: 3560,
    reservedMeters: 710,
    unitPrice: 38,
    status: "available",
  },
  {
    id: "fab-structured-suiting",
    sku: "FL-301",
    name: "Structured Suiting",
    category: "Suiting",
    composition: "58% Wool / 42% Polyester",
    colorway: "Midnight Slate",
    widthCm: 152,
    weightGsm: 285,
    stockMeters: 2680,
    reservedMeters: 980,
    unitPrice: 64,
    status: "available",
  },
  {
    id: "fab-velvet-accent",
    sku: "FL-411",
    name: "Velvet Accent",
    category: "Velvet",
    composition: "82% Polyester / 18% Cotton",
    colorway: "Burnished Copper",
    widthCm: 142,
    weightGsm: 330,
    stockMeters: 980,
    reservedMeters: 610,
    unitPrice: 58,
    status: "low",
  },
  {
    id: "fab-coastal-sheer",
    sku: "FL-227",
    name: "Coastal Drapery Sheer",
    category: "Sheer",
    composition: "54% Linen / 46% Polyester",
    colorway: "Pearl Fog",
    widthCm: 300,
    weightGsm: 145,
    stockMeters: 1840,
    reservedMeters: 640,
    unitPrice: 41,
    status: "available",
  },
  {
    id: "fab-utility-twill",
    sku: "FL-154",
    name: "Utility Cotton Twill",
    category: "Twill",
    composition: "88% Cotton / 12% Nylon",
    colorway: "Desert Clay",
    widthCm: 150,
    weightGsm: 260,
    stockMeters: 1650,
    reservedMeters: 1120,
    unitPrice: 44,
    status: "reserved",
  },
  {
    id: "fab-heritage-boucle",
    sku: "FL-338",
    name: "Heritage Wool Boucle",
    category: "Boucle",
    composition: "64% Wool / 24% Acrylic / 12% Polyester",
    colorway: "Heather Taupe",
    widthCm: 148,
    weightGsm: 295,
    stockMeters: 1260,
    reservedMeters: 420,
    unitPrice: 72,
    status: "available",
  },
]);
